### PR TITLE
Release 7.0.1

### PR DESCRIPTION
**Pull request by BrianBatchelder**
Discovered a few issues while working on Cordova:
- Our minSdkVersion was too low, and conflicted with other plugins. Turns out it is no longer necessary, so I removed it.
- The `create_sample.sh` script didn't capture the current working directory correctly if run from outside the repo root.
- Android libraries version 28 alpha is out, and that is causing some build failures. Changed the dependencies to exclude version 28 for the time being.
- Upgraded to UA Android SDK 9.0.2 & UA iOS SDK 9.0.3

### CODE REVIEW

**Comment by rlepinski** [comment]
Need to do a full release with this.

👍

**Comment by BrianBatchelder** [comment]
Changing PR to release.

**Comment by BrianBatchelder** [comment]
Changing PR to release.

**Comment by ibcooley** [comment]
Thanks for this.  We are currently having are builds break due to the new Android 28 SDK.

**Comment by ibcooley** [comment]
Curious though, to prevent this from breaking in the future.  Could we specify the targets to be like this:

compile 'com.android.support:support-v4:27.+'
?

**Comment by rlepinski** [comment]
@ibcooley 

The main problem is other plugins usually specify `+` for support versions / play services version causing version mismatches with our plugin. Its been an on going issue that I would love to get passed, but I am not sure how to fix it ATM. What we have now is basically `27.+`.

**Comment by rlepinski** [comment]
👍

**Comment by ibcooley** [comment]
Do you guys know when this release will be ready?

**Comment by crow** [comment]
:hamburger:

**Comment by rlepinski** [comment]
@ibcooley just published it

**Comment by ibcooley** [comment]
Thanks for the fast response on this issue everyone.

**Pull request merged**
