### PR TITLE
Push sound android

### PR DESCRIPTION
**Pull request by zachawilson**
Add option to have a sound associated with notification on Android.

### CODE REVIEW

**Comment by rlepinski** [comment]
This looks great. Before I am able to merge it, I need you to sign a contribution agreement -  http://urbanairship.com/legal/contribution-agreement/, however that page is currently down. I am trying to get it back up ASAP so we can get this in.

**Comment by rlepinski** [comment]
Everything is up again. Could you fill out a contribution agreement? http://docs.urbanairship.com/contribution-agreement.html

Thanks!

**Comment by rodrigoplant** [comment]
@rlepinski could you officially merge this feature?

**Comment by zachawilson** [comment]
@rlepinski I filled out the contribution agreement.

**Comment by rlepinski** [comment]
Yep. Thanks!

**Pull request merged**
